[package]
name = "lightmark"
version = "0.2.0"
edition = "2024"

[dependencies]
slint = { version = "1.18", features = ["raw-window-handle-06"] }
ropey = { version = "2.0.0-beta.1", features = ["metric_lines_unicode", "metric_lines_lf"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "arbitrary_precision"] }
pulldown-cmark = "0.13"
regex = "1"
rfd = "0.15"
time = "0.3"
arboard = "3"

[build-dependencies]
slint-build = "1.18"
