[package]
name = "lightmark"
version = "0.2.0"
edition = "2024"

[dependencies]
slint = { version = "1.18", features = ["raw-window-handle-06"] }
ropey = { version = "2.0.0-beta.1", features = ["metric_lines_unicode", "metric_lines_lf"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "arbitrary_precision"] }
pulldown-cmark = "0.13"
regex = "1"
rfd = "0.15"
time = { version = "0.3", features = ["local-offset"] }
unicode-linebreak = "0.1"
ureq = { version = "3.4", default-features = false, features = ["native-tls-no-default"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security_Credentials", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi"] }
arboard = "3"

[build-dependencies]
slint-build = "1.18"
